import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import { Roboto_Flex } from "next/font/google";
import { Roboto_Serif } from "next/font/google";
import { Sancreek } from "next/font/google";
import localFont from "next/font/local";

import { GraphqlProvider } from "@/app/providers/graphql";
import "@/app/styles/index.scss";
import { Footer } from "@/widgets/Footer";
import { Navbar } from "@/widgets/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const robotoSlab = Roboto_Slab({
	subsets: ["latin"],
	display: "swap",
	variable: "--roboto-slab",
});

export const robotoFlex = Roboto_Flex({
	subsets: ["latin"],
	display: "swap",
	variable: "--roboto-flex",
});

export const robotoSerif = Roboto_Serif({
	subsets: ["latin"],
	display: "swap",
	variable: "--roboto-serif",
});

export const sancreek = Sancreek({
	subsets: ["latin"],
	weight: ["400"],
	display: "swap",
	variable: "--sancreek",
});

export const algerian = localFont({
	src: "../public/fonts/algerian.ttf",
	variable: "--algerian",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={clsx(
				algerian.variable,
				robotoSlab.variable,
				robotoFlex.variable,
				robotoSerif.variable,
				sancreek.variable,
			)}
		>
			<body>
				<GraphqlProvider>
					<Navbar />
					{children}
					<Footer />
				</GraphqlProvider>
			</body>
		</html>
	);
}
